export const mockData = [{
    id: "8996918996",
    type: "PushEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 168624843,
      name: "Kikisek/personal-project-react",
      url: "https://api.github.com/repos/Kikisek/personal-project-react"
    },
    payload: {
      push_id: 3268462193,
      size: 2,
      distinct_size: 2,
      ref: "refs/heads/master",
      head: "e63c86fa1a1a18a15de5371a859ccd484581f983",
      before: "6b74ad8338d002e91a6774310d3aa2ab92f15ec5",
      commits: [{
          sha: "26400fc936ecd0f9c7d13db4f88633a91ff2a507",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Create login form",
          distinct: true,
          url: "https://api.github.com/repos/Kikisek/personal-project-react/commits/26400fc936ecd0f9c7d13db4f88633a91ff2a507"
        },
        {
          sha: "e63c86fa1a1a18a15de5371a859ccd484581f983",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Add and parse mock data, display PR titles",
          distinct: true,
          url: "https://api.github.com/repos/Kikisek/personal-project-react/commits/e63c86fa1a1a18a15de5371a859ccd484581f983"
        }
      ]
    },
    public: true,
    created_at: "2019-02-02T06:19:49Z"
  },
  {
    id: "8989872745",
    type: "PushEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 168624843,
      name: "Kikisek/personal-project-react",
      url: "https://api.github.com/repos/Kikisek/personal-project-react"
    },
    payload: {
      push_id: 3264702477,
      size: 1,
      distinct_size: 1,
      ref: "refs/heads/master",
      head: "6b74ad8338d002e91a6774310d3aa2ab92f15ec5",
      before: "684ae6d2609dee989b85cfec1f3142c0b281f1bd",
      commits: [{
        sha: "6b74ad8338d002e91a6774310d3aa2ab92f15ec5",
        author: {
          email: "kristyna@rewardops.com",
          name: "Kristyna Svecova"
        },
        message: "Initial commit",
        distinct: true,
        url: "https://api.github.com/repos/Kikisek/personal-project-react/commits/6b74ad8338d002e91a6774310d3aa2ab92f15ec5"
      }]
    },
    public: true,
    created_at: "2019-02-01T01:52:47Z"
  },
  {
    id: "8989828536",
    type: "ForkEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 168412238,
      name: "bridge-school/personal-project-react",
      url: "https://api.github.com/repos/bridge-school/personal-project-react"
    },
    payload: {
      forkee: {
        id: 168624843,
        node_id: "MDEwOlJlcG9zaXRvcnkxNjg2MjQ4NDM=",
        name: "personal-project-react",
        full_name: "Kikisek/personal-project-react",
        private: false,
        owner: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        html_url: "https://github.com/Kikisek/personal-project-react",
        description: null,
        fork: true,
        url: "https://api.github.com/repos/Kikisek/personal-project-react",
        forks_url: "https://api.github.com/repos/Kikisek/personal-project-react/forks",
        keys_url: "https://api.github.com/repos/Kikisek/personal-project-react/keys{/key_id}",
        collaborators_url: "https://api.github.com/repos/Kikisek/personal-project-react/collaborators{/collaborator}",
        teams_url: "https://api.github.com/repos/Kikisek/personal-project-react/teams",
        hooks_url: "https://api.github.com/repos/Kikisek/personal-project-react/hooks",
        issue_events_url: "https://api.github.com/repos/Kikisek/personal-project-react/issues/events{/number}",
        events_url: "https://api.github.com/repos/Kikisek/personal-project-react/events",
        assignees_url: "https://api.github.com/repos/Kikisek/personal-project-react/assignees{/user}",
        branches_url: "https://api.github.com/repos/Kikisek/personal-project-react/branches{/branch}",
        tags_url: "https://api.github.com/repos/Kikisek/personal-project-react/tags",
        blobs_url: "https://api.github.com/repos/Kikisek/personal-project-react/git/blobs{/sha}",
        git_tags_url: "https://api.github.com/repos/Kikisek/personal-project-react/git/tags{/sha}",
        git_refs_url: "https://api.github.com/repos/Kikisek/personal-project-react/git/refs{/sha}",
        trees_url: "https://api.github.com/repos/Kikisek/personal-project-react/git/trees{/sha}",
        statuses_url: "https://api.github.com/repos/Kikisek/personal-project-react/statuses/{sha}",
        languages_url: "https://api.github.com/repos/Kikisek/personal-project-react/languages",
        stargazers_url: "https://api.github.com/repos/Kikisek/personal-project-react/stargazers",
        contributors_url: "https://api.github.com/repos/Kikisek/personal-project-react/contributors",
        subscribers_url: "https://api.github.com/repos/Kikisek/personal-project-react/subscribers",
        subscription_url: "https://api.github.com/repos/Kikisek/personal-project-react/subscription",
        commits_url: "https://api.github.com/repos/Kikisek/personal-project-react/commits{/sha}",
        git_commits_url: "https://api.github.com/repos/Kikisek/personal-project-react/git/commits{/sha}",
        comments_url: "https://api.github.com/repos/Kikisek/personal-project-react/comments{/number}",
        issue_comment_url: "https://api.github.com/repos/Kikisek/personal-project-react/issues/comments{/number}",
        contents_url: "https://api.github.com/repos/Kikisek/personal-project-react/contents/{+path}",
        compare_url: "https://api.github.com/repos/Kikisek/personal-project-react/compare/{base}...{head}",
        merges_url: "https://api.github.com/repos/Kikisek/personal-project-react/merges",
        archive_url: "https://api.github.com/repos/Kikisek/personal-project-react/{archive_format}{/ref}",
        downloads_url: "https://api.github.com/repos/Kikisek/personal-project-react/downloads",
        issues_url: "https://api.github.com/repos/Kikisek/personal-project-react/issues{/number}",
        pulls_url: "https://api.github.com/repos/Kikisek/personal-project-react/pulls{/number}",
        milestones_url: "https://api.github.com/repos/Kikisek/personal-project-react/milestones{/number}",
        notifications_url: "https://api.github.com/repos/Kikisek/personal-project-react/notifications{?since,all,participating}",
        labels_url: "https://api.github.com/repos/Kikisek/personal-project-react/labels{/name}",
        releases_url: "https://api.github.com/repos/Kikisek/personal-project-react/releases{/id}",
        deployments_url: "https://api.github.com/repos/Kikisek/personal-project-react/deployments",
        created_at: "2019-02-01T01:39:30Z",
        updated_at: "2019-01-31T16:15:11Z",
        pushed_at: "2019-01-31T16:15:09Z",
        git_url: "git://github.com/Kikisek/personal-project-react.git",
        ssh_url: "git@github.com:Kikisek/personal-project-react.git",
        clone_url: "https://github.com/Kikisek/personal-project-react.git",
        svn_url: "https://github.com/Kikisek/personal-project-react",
        homepage: null,
        size: 4,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: false,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        open_issues_count: 0,
        license: null,
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: "master",
        public: true
      }
    },
    public: true,
    created_at: "2019-02-01T01:39:30Z",
    org: {
      id: 30509997,
      login: "bridge-school",
      gravatar_id: "",
      url: "https://api.github.com/orgs/bridge-school",
      avatar_url: "https://avatars.githubusercontent.com/u/30509997?"
    }
  },
  {
    id: "8808356836",
    type: "PushEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Kikisek.github.io",
      url: "https://api.github.com/repos/Kikisek/Kikisek.github.io"
    },
    payload: {
      push_id: 3166996700,
      size: 2,
      distinct_size: 1,
      ref: "refs/heads/master",
      head: "1847eb7e8fb88da5adc6aa6a9f5318200aa237d0",
      before: "2cfe61057fb00d0912f3e188e0c6eccd51dfd01b",
      commits: [{
          sha: "01b7d9ef3b9e7462201f9951c63100da6d83c6da",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Add form templates",
          distinct: false,
          url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/commits/01b7d9ef3b9e7462201f9951c63100da6d83c6da"
        },
        {
          sha: "1847eb7e8fb88da5adc6aa6a9f5318200aa237d0",
          author: {
            email: "30747712+Kikisek@users.noreply.github.com",
            name: "Kristyna Svecova"
          },
          message: "Merge pull request #2 from Kikisek/session-3 Add form templates",
          distinct: true,
          url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/commits/1847eb7e8fb88da5adc6aa6a9f5318200aa237d0"
        }
      ]
    },
    public: true,
    created_at: "2018-12-27T14:23:21Z"
  },
  {
    id: "8808356800",
    type: "PullRequestEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Kikisek.github.io",
      url: "https://api.github.com/repos/Kikisek/Kikisek.github.io"
    },
    payload: {
      action: "closed",
      number: 2,
      pull_request: {
        url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2",
        id: 241163077,
        node_id: "MDExOlB1bGxSZXF1ZXN0MjQxMTYzMDc3",
        html_url: "https://github.com/Kikisek/Kikisek.github.io/pull/2",
        diff_url: "https://github.com/Kikisek/Kikisek.github.io/pull/2.diff",
        patch_url: "https://github.com/Kikisek/Kikisek.github.io/pull/2.patch",
        issue_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2",
        number: 2,
        state: "closed",
        locked: false,
        title: "Add form templates",
        user: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        body: "Add templates and stylesheets for form to filter neighbourhoods.",
        created_at: "2018-12-27T14:23:13Z",
        updated_at: "2018-12-27T14:23:20Z",
        closed_at: "2018-12-27T14:23:20Z",
        merged_at: "2018-12-27T14:23:20Z",
        merge_commit_sha: "1847eb7e8fb88da5adc6aa6a9f5318200aa237d0",
        assignee: null,
        assignees: [],
        requested_reviewers: [],
        requested_teams: [],
        labels: [],
        milestone: null,
        commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/commits",
        review_comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/comments",
        review_comment_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/comments{/number}",
        comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2/comments",
        statuses_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/01b7d9ef3b9e7462201f9951c63100da6d83c6da",
        head: {
          label: "Kikisek:session-3",
          ref: "session-3",
          sha: "01b7d9ef3b9e7462201f9951c63100da6d83c6da",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Kikisek.github.io",
            full_name: "Kikisek/Kikisek.github.io",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Kikisek.github.io",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Kikisek.github.io",
            forks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-12-27T14:20:33Z",
            pushed_at: "2018-12-27T14:23:20Z",
            git_url: "git://github.com/Kikisek/Kikisek.github.io.git",
            ssh_url: "git@github.com:Kikisek/Kikisek.github.io.git",
            clone_url: "https://github.com/Kikisek/Kikisek.github.io.git",
            svn_url: "https://github.com/Kikisek/Kikisek.github.io",
            homepage: null,
            size: 25,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: true,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 0,
            license: null,
            forks: 0,
            open_issues: 0,
            watchers: 0,
            default_branch: "master"
          }
        },
        base: {
          label: "Kikisek:master",
          ref: "master",
          sha: "2cfe61057fb00d0912f3e188e0c6eccd51dfd01b",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Kikisek.github.io",
            full_name: "Kikisek/Kikisek.github.io",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Kikisek.github.io",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Kikisek.github.io",
            forks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-12-27T14:20:33Z",
            pushed_at: "2018-12-27T14:23:20Z",
            git_url: "git://github.com/Kikisek/Kikisek.github.io.git",
            ssh_url: "git@github.com:Kikisek/Kikisek.github.io.git",
            clone_url: "https://github.com/Kikisek/Kikisek.github.io.git",
            svn_url: "https://github.com/Kikisek/Kikisek.github.io",
            homepage: null,
            size: 25,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: true,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 0,
            license: null,
            forks: 0,
            open_issues: 0,
            watchers: 0,
            default_branch: "master"
          }
        },
        _links: {
          self: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2"
          },
          html: {
            href: "https://github.com/Kikisek/Kikisek.github.io/pull/2"
          },
          issue: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2"
          },
          comments: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2/comments"
          },
          review_comments: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/comments"
          },
          review_comment: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/comments{/number}"
          },
          commits: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/commits"
          },
          statuses: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/01b7d9ef3b9e7462201f9951c63100da6d83c6da"
          }
        },
        author_association: "OWNER",
        merged: true,
        mergeable: null,
        rebaseable: null,
        mergeable_state: "unknown",
        merged_by: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        comments: 0,
        review_comments: 0,
        maintainer_can_modify: false,
        commits: 1,
        additions: 1323,
        deletions: 0,
        changed_files: 8
      }
    },
    public: true,
    created_at: "2018-12-27T14:23:21Z"
  },
  {
    id: "8808356390",
    type: "PullRequestEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Kikisek.github.io",
      url: "https://api.github.com/repos/Kikisek/Kikisek.github.io"
    },
    payload: {
      action: "opened",
      number: 2,
      pull_request: {
        url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2",
        id: 241163077,
        node_id: "MDExOlB1bGxSZXF1ZXN0MjQxMTYzMDc3",
        html_url: "https://github.com/Kikisek/Kikisek.github.io/pull/2",
        diff_url: "https://github.com/Kikisek/Kikisek.github.io/pull/2.diff",
        patch_url: "https://github.com/Kikisek/Kikisek.github.io/pull/2.patch",
        issue_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2",
        number: 2,
        state: "open",
        locked: false,
        title: "Add form templates",
        user: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        body: "Add templates and stylesheets for form to filter neighbourhoods.",
        created_at: "2018-12-27T14:23:13Z",
        updated_at: "2018-12-27T14:23:13Z",
        closed_at: null,
        merged_at: null,
        merge_commit_sha: null,
        assignee: null,
        assignees: [],
        requested_reviewers: [],
        requested_teams: [],
        labels: [],
        milestone: null,
        commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/commits",
        review_comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/comments",
        review_comment_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/comments{/number}",
        comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2/comments",
        statuses_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/01b7d9ef3b9e7462201f9951c63100da6d83c6da",
        head: {
          label: "Kikisek:session-3",
          ref: "session-3",
          sha: "01b7d9ef3b9e7462201f9951c63100da6d83c6da",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Kikisek.github.io",
            full_name: "Kikisek/Kikisek.github.io",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Kikisek.github.io",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Kikisek.github.io",
            forks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-12-27T14:20:33Z",
            pushed_at: "2018-12-27T14:10:00Z",
            git_url: "git://github.com/Kikisek/Kikisek.github.io.git",
            ssh_url: "git@github.com:Kikisek/Kikisek.github.io.git",
            clone_url: "https://github.com/Kikisek/Kikisek.github.io.git",
            svn_url: "https://github.com/Kikisek/Kikisek.github.io",
            homepage: null,
            size: 25,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: true,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 1,
            license: null,
            forks: 0,
            open_issues: 1,
            watchers: 0,
            default_branch: "master"
          }
        },
        base: {
          label: "Kikisek:master",
          ref: "master",
          sha: "2cfe61057fb00d0912f3e188e0c6eccd51dfd01b",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Kikisek.github.io",
            full_name: "Kikisek/Kikisek.github.io",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Kikisek.github.io",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Kikisek.github.io",
            forks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Kikisek.github.io/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-12-27T14:20:33Z",
            pushed_at: "2018-12-27T14:10:00Z",
            git_url: "git://github.com/Kikisek/Kikisek.github.io.git",
            ssh_url: "git@github.com:Kikisek/Kikisek.github.io.git",
            clone_url: "https://github.com/Kikisek/Kikisek.github.io.git",
            svn_url: "https://github.com/Kikisek/Kikisek.github.io",
            homepage: null,
            size: 25,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: true,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 1,
            license: null,
            forks: 0,
            open_issues: 1,
            watchers: 0,
            default_branch: "master"
          }
        },
        _links: {
          self: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2"
          },
          html: {
            href: "https://github.com/Kikisek/Kikisek.github.io/pull/2"
          },
          issue: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2"
          },
          comments: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/issues/2/comments"
          },
          review_comments: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/comments"
          },
          review_comment: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/comments{/number}"
          },
          commits: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/pulls/2/commits"
          },
          statuses: {
            href: "https://api.github.com/repos/Kikisek/Kikisek.github.io/statuses/01b7d9ef3b9e7462201f9951c63100da6d83c6da"
          }
        },
        author_association: "OWNER",
        merged: false,
        mergeable: null,
        rebaseable: null,
        mergeable_state: "unknown",
        merged_by: null,
        comments: 0,
        review_comments: 0,
        maintainer_can_modify: false,
        commits: 1,
        additions: 1323,
        deletions: 0,
        changed_files: 8
      }
    },
    public: true,
    created_at: "2018-12-27T14:23:13Z"
  },
  {
    id: "8808309769",
    type: "CreateEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      ref: "session-3",
      ref_type: "branch",
      master_branch: "master",
      description: null,
      pusher_type: "user"
    },
    public: true,
    created_at: "2018-12-27T14:10:00Z"
  },
  {
    id: "8795332689",
    type: "PushEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      push_id: 3159470373,
      size: 4,
      distinct_size: 1,
      ref: "refs/heads/master",
      head: "2cfe61057fb00d0912f3e188e0c6eccd51dfd01b",
      before: "2e39f037e74abdd64812095b7ec646bbfa324672",
      commits: [{
          sha: "afd1c3d107e5ba69c2a1ca78923f2dfea90f2863",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Add locations and neighbourhoods",
          distinct: false,
          url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/afd1c3d107e5ba69c2a1ca78923f2dfea90f2863"
        },
        {
          sha: "d2076a48b73d1afc88f6cae6d52a70a34bef4b67",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Fix searching with coords",
          distinct: false,
          url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/d2076a48b73d1afc88f6cae6d52a70a34bef4b67"
        },
        {
          sha: "670c3a3ac57a83a2f4929d909e5efe7b6907b051",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Enable CORS",
          distinct: false,
          url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/670c3a3ac57a83a2f4929d909e5efe7b6907b051"
        },
        {
          sha: "2cfe61057fb00d0912f3e188e0c6eccd51dfd01b",
          author: {
            email: "30747712+Kikisek@users.noreply.github.com",
            name: "Kristyna Svecova"
          },
          message: "Merge pull request #1 from Kikisek/session-2 Session 2",
          distinct: true,
          url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/2cfe61057fb00d0912f3e188e0c6eccd51dfd01b"
        }
      ]
    },
    public: true,
    created_at: "2018-12-22T14:34:08Z"
  },
  {
    id: "8795332676",
    type: "PullRequestEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      action: "closed",
      number: 1,
      pull_request: {
        url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1",
        id: 240638011,
        node_id: "MDExOlB1bGxSZXF1ZXN0MjQwNjM4MDEx",
        html_url: "https://github.com/Kikisek/Rails-test-app/pull/1",
        diff_url: "https://github.com/Kikisek/Rails-test-app/pull/1.diff",
        patch_url: "https://github.com/Kikisek/Rails-test-app/pull/1.patch",
        issue_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1",
        number: 1,
        state: "closed",
        locked: false,
        title: "Session 2",
        user: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        body: "Add locations and neighbourhoods, check query params, enable CORS.",
        created_at: "2018-12-22T14:33:01Z",
        updated_at: "2018-12-22T14:34:08Z",
        closed_at: "2018-12-22T14:34:08Z",
        merged_at: "2018-12-22T14:34:07Z",
        merge_commit_sha: "2cfe61057fb00d0912f3e188e0c6eccd51dfd01b",
        assignee: null,
        assignees: [],
        requested_reviewers: [],
        requested_teams: [],
        labels: [],
        milestone: null,
        commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/commits",
        review_comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/comments",
        review_comment_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/comments{/number}",
        comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1/comments",
        statuses_url: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/670c3a3ac57a83a2f4929d909e5efe7b6907b051",
        head: {
          label: "Kikisek:session-2",
          ref: "session-2",
          sha: "670c3a3ac57a83a2f4929d909e5efe7b6907b051",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Rails-test-app",
            full_name: "Kikisek/Rails-test-app",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Rails-test-app",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Rails-test-app",
            forks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Rails-test-app/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Rails-test-app/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Rails-test-app/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Rails-test-app/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Rails-test-app/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Rails-test-app/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Rails-test-app/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Rails-test-app/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Rails-test-app/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Rails-test-app/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Rails-test-app/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Rails-test-app/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Rails-test-app/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-11-07T01:39:23Z",
            pushed_at: "2018-12-22T14:34:07Z",
            git_url: "git://github.com/Kikisek/Rails-test-app.git",
            ssh_url: "git@github.com:Kikisek/Rails-test-app.git",
            clone_url: "https://github.com/Kikisek/Rails-test-app.git",
            svn_url: "https://github.com/Kikisek/Rails-test-app",
            homepage: null,
            size: 23,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 0,
            license: null,
            forks: 0,
            open_issues: 0,
            watchers: 0,
            default_branch: "master"
          }
        },
        base: {
          label: "Kikisek:master",
          ref: "master",
          sha: "2e39f037e74abdd64812095b7ec646bbfa324672",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Rails-test-app",
            full_name: "Kikisek/Rails-test-app",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Rails-test-app",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Rails-test-app",
            forks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Rails-test-app/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Rails-test-app/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Rails-test-app/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Rails-test-app/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Rails-test-app/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Rails-test-app/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Rails-test-app/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Rails-test-app/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Rails-test-app/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Rails-test-app/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Rails-test-app/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Rails-test-app/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Rails-test-app/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-11-07T01:39:23Z",
            pushed_at: "2018-12-22T14:34:07Z",
            git_url: "git://github.com/Kikisek/Rails-test-app.git",
            ssh_url: "git@github.com:Kikisek/Rails-test-app.git",
            clone_url: "https://github.com/Kikisek/Rails-test-app.git",
            svn_url: "https://github.com/Kikisek/Rails-test-app",
            homepage: null,
            size: 23,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 0,
            license: null,
            forks: 0,
            open_issues: 0,
            watchers: 0,
            default_branch: "master"
          }
        },
        _links: {
          self: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1"
          },
          html: {
            href: "https://github.com/Kikisek/Rails-test-app/pull/1"
          },
          issue: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1"
          },
          comments: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1/comments"
          },
          review_comments: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/comments"
          },
          review_comment: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/comments{/number}"
          },
          commits: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/commits"
          },
          statuses: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/670c3a3ac57a83a2f4929d909e5efe7b6907b051"
          }
        },
        author_association: "OWNER",
        merged: true,
        mergeable: null,
        rebaseable: null,
        mergeable_state: "unknown",
        merged_by: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        comments: 0,
        review_comments: 0,
        maintainer_can_modify: false,
        commits: 3,
        additions: 139,
        deletions: 1,
        changed_files: 14
      }
    },
    public: true,
    created_at: "2018-12-22T14:34:08Z"
  },
  {
    id: "8795331212",
    type: "PullRequestEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      action: "opened",
      number: 1,
      pull_request: {
        url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1",
        id: 240638011,
        node_id: "MDExOlB1bGxSZXF1ZXN0MjQwNjM4MDEx",
        html_url: "https://github.com/Kikisek/Rails-test-app/pull/1",
        diff_url: "https://github.com/Kikisek/Rails-test-app/pull/1.diff",
        patch_url: "https://github.com/Kikisek/Rails-test-app/pull/1.patch",
        issue_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1",
        number: 1,
        state: "open",
        locked: false,
        title: "Session 2",
        user: {
          login: "Kikisek",
          id: 30747712,
          node_id: "MDQ6VXNlcjMwNzQ3NzEy",
          avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
          gravatar_id: "",
          url: "https://api.github.com/users/Kikisek",
          html_url: "https://github.com/Kikisek",
          followers_url: "https://api.github.com/users/Kikisek/followers",
          following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
          gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
          starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
          organizations_url: "https://api.github.com/users/Kikisek/orgs",
          repos_url: "https://api.github.com/users/Kikisek/repos",
          events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
          received_events_url: "https://api.github.com/users/Kikisek/received_events",
          type: "User",
          site_admin: false
        },
        body: "Add locations and neighbourhoods, check query params, enable CORS.",
        created_at: "2018-12-22T14:33:01Z",
        updated_at: "2018-12-22T14:33:01Z",
        closed_at: null,
        merged_at: null,
        merge_commit_sha: null,
        assignee: null,
        assignees: [],
        requested_reviewers: [],
        requested_teams: [],
        labels: [],
        milestone: null,
        commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/commits",
        review_comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/comments",
        review_comment_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/comments{/number}",
        comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1/comments",
        statuses_url: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/670c3a3ac57a83a2f4929d909e5efe7b6907b051",
        head: {
          label: "Kikisek:session-2",
          ref: "session-2",
          sha: "670c3a3ac57a83a2f4929d909e5efe7b6907b051",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Rails-test-app",
            full_name: "Kikisek/Rails-test-app",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Rails-test-app",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Rails-test-app",
            forks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Rails-test-app/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Rails-test-app/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Rails-test-app/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Rails-test-app/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Rails-test-app/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Rails-test-app/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Rails-test-app/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Rails-test-app/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Rails-test-app/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Rails-test-app/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Rails-test-app/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Rails-test-app/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Rails-test-app/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-11-07T01:39:23Z",
            pushed_at: "2018-12-22T14:31:12Z",
            git_url: "git://github.com/Kikisek/Rails-test-app.git",
            ssh_url: "git@github.com:Kikisek/Rails-test-app.git",
            clone_url: "https://github.com/Kikisek/Rails-test-app.git",
            svn_url: "https://github.com/Kikisek/Rails-test-app",
            homepage: null,
            size: 23,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 1,
            license: null,
            forks: 0,
            open_issues: 1,
            watchers: 0,
            default_branch: "master"
          }
        },
        base: {
          label: "Kikisek:master",
          ref: "master",
          sha: "2e39f037e74abdd64812095b7ec646bbfa324672",
          user: {
            login: "Kikisek",
            id: 30747712,
            node_id: "MDQ6VXNlcjMwNzQ3NzEy",
            avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/Kikisek",
            html_url: "https://github.com/Kikisek",
            followers_url: "https://api.github.com/users/Kikisek/followers",
            following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
            gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
            starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
            organizations_url: "https://api.github.com/users/Kikisek/orgs",
            repos_url: "https://api.github.com/users/Kikisek/repos",
            events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
            received_events_url: "https://api.github.com/users/Kikisek/received_events",
            type: "User",
            site_admin: false
          },
          repo: {
            id: 156473442,
            node_id: "MDEwOlJlcG9zaXRvcnkxNTY0NzM0NDI=",
            name: "Rails-test-app",
            full_name: "Kikisek/Rails-test-app",
            private: false,
            owner: {
              login: "Kikisek",
              id: 30747712,
              node_id: "MDQ6VXNlcjMwNzQ3NzEy",
              avatar_url: "https://avatars3.githubusercontent.com/u/30747712?v=4",
              gravatar_id: "",
              url: "https://api.github.com/users/Kikisek",
              html_url: "https://github.com/Kikisek",
              followers_url: "https://api.github.com/users/Kikisek/followers",
              following_url: "https://api.github.com/users/Kikisek/following{/other_user}",
              gists_url: "https://api.github.com/users/Kikisek/gists{/gist_id}",
              starred_url: "https://api.github.com/users/Kikisek/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/Kikisek/subscriptions",
              organizations_url: "https://api.github.com/users/Kikisek/orgs",
              repos_url: "https://api.github.com/users/Kikisek/repos",
              events_url: "https://api.github.com/users/Kikisek/events{/privacy}",
              received_events_url: "https://api.github.com/users/Kikisek/received_events",
              type: "User",
              site_admin: false
            },
            html_url: "https://github.com/Kikisek/Rails-test-app",
            description: null,
            fork: false,
            url: "https://api.github.com/repos/Kikisek/Rails-test-app",
            forks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/forks",
            keys_url: "https://api.github.com/repos/Kikisek/Rails-test-app/keys{/key_id}",
            collaborators_url: "https://api.github.com/repos/Kikisek/Rails-test-app/collaborators{/collaborator}",
            teams_url: "https://api.github.com/repos/Kikisek/Rails-test-app/teams",
            hooks_url: "https://api.github.com/repos/Kikisek/Rails-test-app/hooks",
            issue_events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/events{/number}",
            events_url: "https://api.github.com/repos/Kikisek/Rails-test-app/events",
            assignees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/assignees{/user}",
            branches_url: "https://api.github.com/repos/Kikisek/Rails-test-app/branches{/branch}",
            tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/tags",
            blobs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/blobs{/sha}",
            git_tags_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/tags{/sha}",
            git_refs_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/refs{/sha}",
            trees_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/trees{/sha}",
            statuses_url: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/{sha}",
            languages_url: "https://api.github.com/repos/Kikisek/Rails-test-app/languages",
            stargazers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/stargazers",
            contributors_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contributors",
            subscribers_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscribers",
            subscription_url: "https://api.github.com/repos/Kikisek/Rails-test-app/subscription",
            commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits{/sha}",
            git_commits_url: "https://api.github.com/repos/Kikisek/Rails-test-app/git/commits{/sha}",
            comments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/comments{/number}",
            issue_comment_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/comments{/number}",
            contents_url: "https://api.github.com/repos/Kikisek/Rails-test-app/contents/{+path}",
            compare_url: "https://api.github.com/repos/Kikisek/Rails-test-app/compare/{base}...{head}",
            merges_url: "https://api.github.com/repos/Kikisek/Rails-test-app/merges",
            archive_url: "https://api.github.com/repos/Kikisek/Rails-test-app/{archive_format}{/ref}",
            downloads_url: "https://api.github.com/repos/Kikisek/Rails-test-app/downloads",
            issues_url: "https://api.github.com/repos/Kikisek/Rails-test-app/issues{/number}",
            pulls_url: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls{/number}",
            milestones_url: "https://api.github.com/repos/Kikisek/Rails-test-app/milestones{/number}",
            notifications_url: "https://api.github.com/repos/Kikisek/Rails-test-app/notifications{?since,all,participating}",
            labels_url: "https://api.github.com/repos/Kikisek/Rails-test-app/labels{/name}",
            releases_url: "https://api.github.com/repos/Kikisek/Rails-test-app/releases{/id}",
            deployments_url: "https://api.github.com/repos/Kikisek/Rails-test-app/deployments",
            created_at: "2018-11-07T01:36:32Z",
            updated_at: "2018-11-07T01:39:23Z",
            pushed_at: "2018-12-22T14:31:12Z",
            git_url: "git://github.com/Kikisek/Rails-test-app.git",
            ssh_url: "git@github.com:Kikisek/Rails-test-app.git",
            clone_url: "https://github.com/Kikisek/Rails-test-app.git",
            svn_url: "https://github.com/Kikisek/Rails-test-app",
            homepage: null,
            size: 23,
            stargazers_count: 0,
            watchers_count: 0,
            language: "Ruby",
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 1,
            license: null,
            forks: 0,
            open_issues: 1,
            watchers: 0,
            default_branch: "master"
          }
        },
        _links: {
          self: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1"
          },
          html: {
            href: "https://github.com/Kikisek/Rails-test-app/pull/1"
          },
          issue: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1"
          },
          comments: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/issues/1/comments"
          },
          review_comments: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/comments"
          },
          review_comment: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/comments{/number}"
          },
          commits: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/pulls/1/commits"
          },
          statuses: {
            href: "https://api.github.com/repos/Kikisek/Rails-test-app/statuses/670c3a3ac57a83a2f4929d909e5efe7b6907b051"
          }
        },
        author_association: "OWNER",
        merged: false,
        mergeable: null,
        rebaseable: null,
        mergeable_state: "unknown",
        merged_by: null,
        comments: 0,
        review_comments: 0,
        maintainer_can_modify: false,
        commits: 3,
        additions: 139,
        deletions: 1,
        changed_files: 14
      }
    },
    public: true,
    created_at: "2018-12-22T14:33:01Z"
  },
  {
    id: "8795328679",
    type: "PushEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      push_id: 3159467811,
      size: 2,
      distinct_size: 2,
      ref: "refs/heads/session-2",
      head: "670c3a3ac57a83a2f4929d909e5efe7b6907b051",
      before: "afd1c3d107e5ba69c2a1ca78923f2dfea90f2863",
      commits: [{
          sha: "d2076a48b73d1afc88f6cae6d52a70a34bef4b67",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Fix searching with coords",
          distinct: true,
          url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/d2076a48b73d1afc88f6cae6d52a70a34bef4b67"
        },
        {
          sha: "670c3a3ac57a83a2f4929d909e5efe7b6907b051",
          author: {
            email: "kristyna@rewardops.com",
            name: "Kristyna Svecova"
          },
          message: "Enable CORS",
          distinct: true,
          url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/670c3a3ac57a83a2f4929d909e5efe7b6907b051"
        }
      ]
    },
    public: true,
    created_at: "2018-12-22T14:31:13Z"
  },
  {
    id: "8717593489",
    type: "CreateEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      ref: "session-2",
      ref_type: "branch",
      master_branch: "master",
      description: null,
      pusher_type: "user"
    },
    public: true,
    created_at: "2018-12-07T17:38:02Z"
  },
  {
    id: "8546735565",
    type: "PushEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      push_id: 3026293507,
      size: 1,
      distinct_size: 1,
      ref: "refs/heads/master",
      head: "2e39f037e74abdd64812095b7ec646bbfa324672",
      before: "f897ccd4ba69573ac44129ac469150bada951571",
      commits: [{
        sha: "2e39f037e74abdd64812095b7ec646bbfa324672",
        author: {
          email: "kristyna@rewardops.com",
          name: "Kristyna Svecova"
        },
        message: "Set up Rails app",
        distinct: true,
        url: "https://api.github.com/repos/Kikisek/Rails-test-app/commits/2e39f037e74abdd64812095b7ec646bbfa324672"
      }]
    },
    public: true,
    created_at: "2018-11-07T01:39:22Z"
  },
  {
    id: "8546726394",
    type: "CreateEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      ref: "master",
      ref_type: "branch",
      master_branch: "master",
      description: null,
      pusher_type: "user"
    },
    public: true,
    created_at: "2018-11-07T01:36:33Z"
  },
  {
    id: "8546726335",
    type: "CreateEvent",
    actor: {
      id: 30747712,
      login: "Kikisek",
      display_login: "Kikisek",
      gravatar_id: "",
      url: "https://api.github.com/users/Kikisek",
      avatar_url: "https://avatars.githubusercontent.com/u/30747712?"
    },
    repo: {
      id: 156473442,
      name: "Kikisek/Rails-test-app",
      url: "https://api.github.com/repos/Kikisek/Rails-test-app"
    },
    payload: {
      ref: null,
      ref_type: "repository",
      master_branch: "master",
      description: null,
      pusher_type: "user"
    },
    public: true,
    created_at: "2018-11-07T01:36:32Z"
  }
]